name: 'PostgreSQL Slow Query Log Analyzer'
description: 'Collect slow query log data and analyze them'
inputs:
  metis_api_key:
    description: metis api key project identifier
    required: true
    default: ''
  github_token:
    description: github token
    required: false
    default: ''
  target_url:
    description: target url
    required: false
    default: 'https://dev.metisdata.io'
  metis_exporter_url:
    description: exporter url
    required: false
    default: 'https://ingest-stg.metisdata.io'
  db_connection_string:
    description: database connection string
    required: true
    default: ''
  queries:
    required: false
    description: sql queries
    default: '[]'
  useRoute:
    required: false
    description: flag that choose if to use route
  qaMode:
    required: false
    description: flag that activate qa-mode
  disableSendDataToMetis:
    required: false
    description: run the queries but dont create spans and pr card - used for query-stats feature
runs:
  using: 'node16'
  main: 'index.js'
