name: 'PostgreSQL Slow Query Log Analyzer'
description: 'Collect slow query log data and analyze them'
inputs:
  metis_api_key:
    description: metis api key project identifier
    required: true
    default: ''
  github_token:
    description: github token
    required: false
    default: ''
  target_url:
    description: target url
    required: false
    default: 'https://dev.metisdata.io'
  metis_exporter_url:
    description: target url
    required: false
    default: 'https://ingest-stg.metisdata.io'
  db_connection_string:
    description: database connection string
    required: true
    default: ''
  query:
    required: true
    description: sql query
    default: 'select * from  postgres_air.boarding_pass as b where passenger_id = "4484038"'
runs:
  using: 'node16'
  main: 'index.js'
